### ISSUE TITLE
Fix setDarkness() and getDarkness() functions

### ISSUE THREAD

**Issue by woxens** [Cruor/LuaCutscenes#11]
get/setDarkness functions currently will get/set bloom strength instead, change code to:

`function helpers.setDarkness(amount)
    engine.Scene.Lighting.Alpha = amount
end

function helpers.getDarkness()
    return engine.Scene.Lighting.Alpha
end`

**Comment by Cruor** [comment]
Implemented now and released in 0.2.13, thanks for the report.
